from parserSQL import *
from executorSQL import *

p = executorSQL.SQLExecuter()
p.execute("show databases")
# p.execute("CREATE DATABASE test_tt")
p.execute("USE test_tt")
# p.execute("CREATE INDEX i ON TABLE2 (COL2)")
# p.execute("CREATE INDEX i2 ON TABLE2 (COL1)")
# p.execute("CREATE INDEX i2 ON TABLE2 (COL1)")
# p.execute("DROP INDEX i ON TABLE2")
# p.execute("CREATE INDEX i ON TABLE2 (COL2)")
# p.execute("SHOW tables")
# p.execute("INSERT INTO TABLE2 VALUES (1, No, 1)")
# p.execute("INSERT INTO TABLE2 VALUES (2, YES, 7)")
# p.execute("INSERT INTO TABLE2 VALUES (3, YES, 6)")
# p.execute("INSERT INTO TABLE2 VALUES (4, YES, 4)")
# p.execute("INSERT INTO TABLE2 VALUES (5, No, 9)")
# p.execute("INSERT INTO TABLE2 VALUES (6, YES, 11)")
# p.execute("INSERT INTO TABLE2 VALUES (7, YES, 15)")
# p.execute("INSERT INTO TABLE2 VALUES (8, YES, 18)")
# p.execute("INSERT INTO TABLE2 VALUES (9, No, 22)")
p.execute("SELECT COUNT(COL1), AVG(COL2), MAX(COL2), MIN(COL2), SUM(COL2) FROM TABLE2")

# p.execute("SELECT count(COL2) FROM TABLE2")
# p.execute("SELECT avg(COL2) FROM TABLE2")
# p.execute("SELECT min(COL2) FROM TABLE2")
# p.execute("SELECT max(COL2) FROM TABLE2")
# p.execute("SELECT AVG(COL2), AVG(COL1) FROM TABLE2 WHERE COL2 > 18 GROUP BY COL3")
# p.execute("SELECT AVG(COL2) FROM TABLE2 GROUP BY COL3")
# p.execute("SELECT * FROM TABLE2 LIMIT 3 ORDER BY COL2")
# p.execute("SELECT * FROM TABLE2 ORDER BY COL2 LIMIT 3")
# p.execute("SELECT * FROM TABLE2 ORDER BY COL2")
# p.execute("SELECT * FROM TABLE2")
# # p.execute("SELECT * FROM TABLE2 GROUP BY COL2")
# # p.execute("SELECT COL2 FROM TABLE2")
# # p.execute("SELECT * FROM TABLE2")
# p.execute("UPDATE TABLE1 set COL1 = 1, COL2 = 2 WHERE COL1 = 1 ")
# # p.execute("SELECT * FROM TABLE2")
# p.execute("SELECT * FROM TABLE2")
# p.execute("DELETE FROM TABLE1 WHERE COL2 = 1 ")
# p.execute("DELETE FROM TABLE1 WHERE COL2 = 1 OR COL1 = No")
# p.execute("DELETE FROM TABLE2 WHERE COL2 = 19")
p.execute("EXIT")
